//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSROLEMGR
    {
        public int Mgr_ID { get; set; }
        public string UserName { get; set; }
        public string Role_Name { get; set; }
        public string Func_Name { get; set; }
        public string C_Action { get; set; }
        public string E_Action { get; set; }
        public string D_Action { get; set; }
        public string A_Action { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Date_Created { get; set; }
    }
}
