//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS_Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSPASSTAB
    {
        public decimal PWD_REC_NO { get; set; }
        public string PWD_GROUP_ID { get; set; }
        public string PWD_ID { get; set; }
        public string PWD_USER_NAME { get; set; }
        public string PWD_CODE { get; set; }
        public string PWD_CODE_RE { get; set; }
        public string PWD_CODE_CHG { get; set; }
        public string PWD_CODE_DEL { get; set; }
        public string PWD_LOGIN_COUNT { get; set; }
        public string PWD_USER_LEVEL { get; set; }
        public string PWD_APPROVED_SW { get; set; }
        public string PWD_LOG_USER { get; set; }
        public string PWD_CTRL_SW { get; set; }
        public Nullable<System.DateTime> PWD_ALERT_DATE { get; set; }
        public Nullable<System.DateTime> PWD_EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> PWD_EXPIRY_DATE { get; set; }
        public string PWD_USER_TYPE { get; set; }
        public string PWD_USER_DEPT { get; set; }
        public Nullable<decimal> PWD_USER_GRP { get; set; }
        public string PWD_ENABLE_SW { get; set; }
        public string PWD_SETUP_SW { get; set; }
        public string PWD_SECURITY_SW { get; set; }
        public string PWD_GENERAL_SW { get; set; }
        public string PWD_MARKETING_SW { get; set; }
        public string PWD_POLICY_SW { get; set; }
        public string PWD_UNDERWRITING_SW { get; set; }
        public string PWD_CLAIMS_SW { get; set; }
        public string PWD_REINSURANCE_SW { get; set; }
        public string PWD_CREDITCONTROL_SW { get; set; }
        public string PWD_ACCOUNTS_SW { get; set; }
        public string PWD_FIXEDASSET_SW { get; set; }
        public string PWD_PAYROLL_SW { get; set; }
        public string PWD_PERSONNEL_SW { get; set; }
        public string PWD_ACCOUNTS_SW_GL { get; set; }
        public string PWD_INVESTMENT_SW { get; set; }
        public string PWD_PURCHASES_SW { get; set; }
        public string PWD_INSERT_SW { get; set; }
        public string PWD_UPDATE_SW { get; set; }
        public string PWD_DELETE_SW { get; set; }
        public string PWD_PRINT_SW { get; set; }
        public string PWD_VIEW_SW { get; set; }
        public string PWD_PROCESS_SW { get; set; }
        public string PWD_MGT_CAT_SW { get; set; }
        public string PWD_MGT_CAT_NUM { get; set; }
        public string PWD_USER_AUTH { get; set; }
        public string PWD_STORE_AUTH { get; set; }
        public string PWD_TEL_NUM { get; set; }
        public string PWD_TELEXT_NUM { get; set; }
        public string PWD_FAX_NUM { get; set; }
        public string PWD_EMAIL_NUM { get; set; }
        public string PWD_MOBILE_NUM { get; set; }
        public string PWD_UND_SPC { get; set; }
        public Nullable<System.DateTime> PWD_LOG_DATE { get; set; }
        public Nullable<System.DateTime> PWD_LOG_TIME { get; set; }
        public Nullable<System.DateTime> PWD_EXIT_DATE { get; set; }
        public string PWD_FLAG { get; set; }
        public Nullable<System.DateTime> PWD_KEYDTE { get; set; }
        public string PWD_OPERID { get; set; }
    }
}
