//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS_Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSROLEUSER
    {
        public string USER_ROLE_ID { get; set; }
        public decimal USER_ROLE_NO { get; set; }
        public string USER_ROLE_USER_ID { get; set; }
        public string USER_ROLE_USER_NAME { get; set; }
        public string USER_ROLE_NUM { get; set; }
        public string USER_ROLE_NAME { get; set; }
        public Nullable<System.DateTime> USER_ROLE_KEYDTE { get; set; }
    }
}
