//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS_Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSROLEDTL
    {
        public string ROLE_DTL_USER_ID { get; set; }
        public string ROLE_DTL_ID { get; set; }
        public string ROLE_DTL_NUM { get; set; }
        public decimal ROLE_DTL_NO { get; set; }
        public string ROLE_DTL_ROLE_NUM { get; set; }
        public string ROLE_DTL_MODULE_NAME { get; set; }
        public string ROLE_DTL_MODULE_TYPE { get; set; }
        public string ROLE_DTL_PERMISSION_YN { get; set; }
        public string ROLE_DTL_INSERT_YN { get; set; }
        public string ROLE_DTL_UPDATE_YN { get; set; }
        public string ROLE_DTL_DELETE_YN { get; set; }
        public string ROLE_DTL_VIEW_YN { get; set; }
        public string ROLE_DTL_PRINT_YN { get; set; }
        public string ROLE_DTL_APPROVE_YN { get; set; }
        public Nullable<decimal> ROLE_DTL_APPROVE_MIN_VALUE { get; set; }
        public Nullable<decimal> ROLE_DTL_APPROVE_MAX_VALUE { get; set; }
        public string ROLE_DTL_FLAG { get; set; }
        public Nullable<System.DateTime> ROLE_DTL_KEYDTE { get; set; }
        public string ROLE_DTL_OPERID { get; set; }
    }
}
