//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS_Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSROLEMST
    {
        public string ROLE_ID { get; set; }
        public string ROLE_NUM { get; set; }
        public decimal ROLE_NO { get; set; }
        public string ROLE_NAME { get; set; }
        public string ROLE_TYPE { get; set; }
        public string ROLE_FLAG { get; set; }
        public System.DateTime ROLE_KEYDTE { get; set; }
        public string ROLE_OPERID { get; set; }
    }
}
