//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS_Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSROLEDETAIL
    {
        public long ROLE_ID { get; set; }
        public string STAFF_NAME { get; set; }
        public string STAFF_EMAIL { get; set; }
        public string USER_ROLE { get; set; }
        public string USER_FUNC { get; set; }
        public string ROLE_INSERT { get; set; }
        public string ROLE_UPDATE { get; set; }
        public string ROLE_DELETE { get; set; }
        public string ROLE_APPROVE { get; set; }
        public string ROLE_FLAG { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime KEYED_DATE { get; set; }
    }
}
