//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS_Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSUSER
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string User_Pass { get; set; }
        public Nullable<int> Login_Count { get; set; }
        public string Email { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Date_Created { get; set; }
    }
}
